drone/drone-plugin-index

content/e20co/drone-marathon/index.md
This functionality has already been included in the `0.5` tag.  This updates the documentation so others can use this as well.  Enjoy!
=> Adds Secrets support to drone-marathon plugin.

content/drillster/drone-rsync/index.md
The rsync plugin recently got an additional parameter to specify additional rsync arguments. This PR updates the docs to reflect this change.
=> Add 'args' parameter to rsync plugin docs

content/drone-plugins/drone-docker/index.md
dns is a reserved word now so the dns property is no longer being
converted to PLUGIN_DNS env var. Updating the name to enable passing
to the plugin
=> Update dns property to custom_dns property

content/drillster/drone-volume-cache/index.md
The docs for the volume-cache plugin were a bit outdated. I've updated them to reflect the new functionality that has been added to the plugin.
=> Update volume-cache docs to reflect new functionality

content/robertstettner/drone-npm-auth/index.md
This PR adds documentation for the following plugin: https://github.com/robertstettner/drone-npm-auth
=> Adds NPM Auth plugin to index

content/robertstettner/drone-mvn-auth/index.md, static/logos/maven.svg
This PR adds documentation for the following plugin: https://github.com/robertstettner/drone-mvn-auth
=> Adds Maven Auth plugin to index

content/drone-plugins/drone-gcr/index.md
Not sure if this is correct (never used Hugo).
Based on docs from https://gohugo.io/content-management/cross-references/.
=> Add link to drone-docker

content/drone-plugins/drone-gcr/index.md
Fixes the builds breaking since https://github.com/drone/drone-plugin-index/pull/66.
Should we run `hugo` on every PR so we can validate compilation?
=> Fix link to drone-docker

content/drone-plugins/drone-s3-cache/index.md
"url" option is missing. 
To specify s3 endpoint, using "endpoint" is best.
https://github.com/drone-plugins/drone-s3-cache/blob/master/main.go#L103
=> fix to use endpoint instead of url option for drone-s3-cache

content/tuannvm/drone-rds-snapper/index.md
- Add plugin to manage RDS snapshot.
- Create new snapshot with customized name suffix.
- Clear old snapshot and keep the latest.
- Print snapshots list to stdout.
=> add rds-snapper plugin

content/gboddin/drone-github-search-downstream/index.md
Is just an extend of `plugins/downstream` ( cc @tboerger ) but allows a list of repositories from a Github search instead of a provided list : 
```
pipeline:
trigger-downstream:
image: gboo/github-search-downstream
github_query: "org:drone-plugins topic:drone-plugin"
branch: master
drone_server: https://hold-on.nobody.run
secrets: [ github_token, drone_token ]
```
Useful if you have lots of repositories tagged by a topic that you want to test in some circumstances for instance
=> Proposing Github search Downstream plugin

content/hvalle/drone-gcs-cache/index.md
This plugin takes the s3 cache plugin and modifies it to use GCS, using service accounts gives better access control than using interoperability.
=>  Add drone-gcs-cache plugin docs

content/drone-plugins/drone-slack/index.md
This never got documented, and it's super useful https://github.com/drone-plugins/drone-slack/pull/71
=> Add documentation for link_names

content/appleboy/drone-apex-up/index.md, static/logos/apex-up.svg
This plugin can deploy infinitely scalable serverless apps, apis, and sites in seconds to AWS using [apex/up](https://github.com/apex/up) tool.
=> feat: add apex/up plugin.

content/drone-plugins/drone-downstream/index.md
The secret name referenced in the documentation example is `docker_token`, but based on the context, it seems like it should be something like `drone_token`.
=> Docs: Fix from_secret name in example

content/cbrgm/drone-hugo/index.md
Updated the drone hugo plugin docs site.
Also added an updated example how to generate static website files and publish them on a remote server.
=> Update hugo plugin docs

content/drone-plugins/drone-github-release/index.md
Should fix https://github.com/drone-plugins/drone-github-release/issues/25
=> github-release: add required scope documentation for access token

content/drone-plugins/drone-ecr/index.md
I tried with just `dns` and it was still failing, but `custom_dns` (as described in the docker plugin's docs page) works perfectly.
=> ECR documentation needs custom_dns since this plugin is combined with the docker plugin

content/drone-plugins/drone-s3/index.md
* Added example on using DRONE_BUILD_NUMBER, since I think this is a common use case, and the syntax for general variable substitution for plugin parameters isn't well documented.
* Added clarification that the source location must be in the drone workspace. This makes sense since the plugin runs in its own container, but can be easy to gloss over. 
Something I wasn't sure of - can you also upload artifacts from a shared volume which is mounted outside the workspace?
=> Doc updates on source and target parameters

content/drone-plugins/drone-pypi/index.md
In the docs it uses `from_password` which is not valid, it should be `from_secret`.
=> typo: from_secret not from_password

content/drone-plugins/drone-docker/index.md
Closes https://github.com/drone-plugins/drone-docker/issues/246
`build_args_from_env` is currently undocumented. This PR adds a brief description about it and also provide a simple example to pass a secret as a build argument (Thanks @Leboudin for the nice example!).
=> Document build_args_from_env of Docker plugin

content/drone-plugins/drone-ecr/index.md
The `repo` parameter seems to take the repo name rather than the URL.
=> Update Drone ECR docs

content/bitsbeats/drone-helm3/index.md
Documentation for bitsbeats/drone-helm3.
The existing helm plugin seems to have gone stale.
=> add helm3 plugin

config.yaml
My original motivation was to fix the pluralization of "Pelotech," which Hugo turned into "Peloteches," but pluralization in general doesn't seem appropriate for the plugin index. It makes sense for something like "posts," but in this case we're looking at author names, not categories.
=> Use singular titles for plugin authors

content/drone-plugins/drone-gitea-release/index.md
=> drone-gitea-release: indent error in yaml of checksum example

content/drone-plugins/drone-ecr/index.md
Made a typo, variable name is `create_repository` and not just `create`. @bradrydzewski sorry just noticed this seconds after you merged #278
=> fix: typo in setting variable name

content/drone-plugins/drone-docker/index.md
the documentation differs from source (https://github.com/drone-plugins/drone-docker/blob/master/cmd/drone-docker/main.go) and I wanted to bring it back in sync
open issues:
* were the parameters "auth" and "force_tag" removed from the source code and are therefore obsolete?
* list is getting long and is hard to grasp, I suggest to sort it alphabetically and add a most used parameters list after the examples
=> WIP: update drone-docker documentation

content/bh90210/dron8s/index.md
hi all,
I really needed the functionality for myself so here it is
https://github.com/bh90210/dron8s
It can behave pretty much like `kubectl apply -f configs.yaml` but from within a pipeline, and achieves that by directly manipulating Kubernetes API via `client-go` and not via `kubectl`.
ps. I would not consider this to be a duplicate of #264 since we solved the problem with two very different ways.
=> kubernetes dynamic server side apply w/ client-go

content/drone-plugins/drone-slack/index.md
The currently linked implementation leads to an error "invalid_token" when trying to use with the plugin. 
The approach that must be followed for creation of the Slack Webhook needs to be as a Slack App. 
Hence, I swapped out the link here so future new starters set up with the correct Webhook and aren't stuck in the same rabbithole as I was.
Ref:https://discourse.drone.io/t/invalid-token-error-message-when-trying-to-use-slack-notifications/8391/2
=> Update url for getting started with slack webhooks

content/drone-plugins/drone-ansible/index.md
Docs reference an old version of the Ansible plugin which is quite buggy. As a newcomer it took me some time to figure out that there was another, newer version of the plugin available.
This PR makes v3 the default from now on.
=> bumps ansible plugin version

content/drone-plugins/drone-ecr/index.md
* adding new scan_on_push parameter to the documentation, which related to this merged feature -  https://github.com/drone-plugins/drone-docker/pull/300
=> drone-ecr: adding new scan_on_push parameter to the documentation

plugins/dco/content.yaml, plugins/dco/original.md
This obsoletes #150.
I had to open a new PR, because the fork #150 was made from has been deleted since, and re-forking didn't link it back, so couldn't update the original PR.
=> Add drone-plugin-dco to the index

.github/stale.yml
To help us maintain a clean backlog of PR's and to give high impact PR's a better chance to be seen, reviewed and merged, we need an automated way of clearing out any PR's that haven't seen any action in a while.
_This initial integration of Stalebot is an experiment._
=> Add Stalebot

plugins/docker/original.md
I encountered errors and went on an adventure enabling logs, diving into the several podman container in container layers to ultimately find the raw docker command executed. With some added words, this info can help the next person without delving into CLIs.
=> Clarify docker plugin parameter dockerfile is a path (not just file name)

plugins/downstream/content.yaml
The fork has been removed from the implementation already. https://github.com/drone-plugins/drone-downstream/commit/acfef233307b3dace22ceffb0ee139ee68a75752
=> Remove the fork option in the doc

plugins/slack-blame/content.yaml
Update the `mapping` option description to include support for environment variable interpolation.
Update `required` for options incorrectly labeled as true.
=> Update slack-blame documentation

plugin-validation/plugin-schema.json, plugins/github-app/content.yaml
adding a new plugin: github token
this was created to simplify using a github app by generating a JWT and GITHUB_TOKEN.
output form is a local file for jwt/token/both.
=> plugin: github app

plugins/jfrog-artifactory/content.yaml
artifactory plugin maintained by harness.
customer support directed a customer to use this plugin, but they were unable to find documentation for it.
Adding it here with the docs so users can see all the options without looking at the code.
There is a current `artifactory` plugin so I prefixed this with `jfrog`, let me know if you have other ideas for conflicting plugins.
=> plugin: jfrog artifactory

plugins/docker/content.yaml
When dry-run is true, the image will *not* be posted. The description made it sound like the opposite would happen.
=> fix explanation dry-run for docker plugin

plugins/qodana-jvm-community-plugin/content.yaml, plugins/qodana-jvm-community-plugin/original.md
This plugin enables the usage of the Qodana JVM Community linter on Drone. It can be used with a Community (free) license of Qodana.
https://github.com/2martens/qodana-jvm-community-drone-plugin
=> Qodana jvm community drone plugin
