content/jmccann/terraform/index.md

Found a couple more hipchat references after seeing you clean some up.  Can you tell what I used as a template? ;)

Remove a couple more hipchat references from terraform

---

content/jmccann/hipchat/index.md

* Fix a plugin reference
* Add notes in secrets section that I think are helpful to people

Updates to hipchat documentation

---

content/appleboy/drone-scp/index.md
content/appleboy/drone-scp/index.zh-tw.md

Add [drone-scp](https://github.com/appleboy/drone-scp) plugin.
cc @bradrydzewski

feat: add drone-scp plugin.

---

content/appleboy/drone-scp/index.md
content/appleboy/drone-scp/index.zh-tw.md

fix: format for scp plugin.

---

content/appleboy/drone-line/index.md
content/appleboy/drone-line/index.zh-tw.md

fix: duplicate of image key.

---

content/appleboy/drone-jenkins/index.md

docs: update jenkins docs

---

content/peloton/drone-rancher/index.md

Adding more options for the Rancher plugin

Update to docs for batch size and intervals for Rancher plugin

---

content/appleboy/drone-ssh/index.md

feat: Add drone-ssh plugin.

---

content/appleboy/drone-scp/index.md

Add example configuration with wildcard pattern of source list.
cc @bradrydzewski

update drone-scp feature.

---

content/mactynow/drone-kubernetes/index.md

This PR adds the documentation for the following plugin : https://github.com/honestbee/drone-kubernetes.

Add drone-kubernetes documentation

---

content/appleboy/drone-scp/index.md
content/appleboy/drone-ssh/index.md

Support `ProxyCommand` for ssh protocol.
Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>

add proxy command docs.

---

content/appleboy/drone-sftp-cache/index.md

fix: typo (update drone-sftp-cache plugin)

---

content/appleboy/drone-telegram/index.md

fix drone-telegram message format.

---

content/appleboy/drone-telegram/index.md

fix https://github.com/appleboy/drone-telegram/issues/38
cc @bradrydzewski

fix wrong format of message field

---

content/e20co/drone-marathon/index.md

We've just updated our drone-marathon plugin to use the new secrets
store in Drone 0.7.  Please note the changes to the `values` list and
how secrets are handled.

Updates drone-marathon plugin docs to Drone 0.7

---

content/drone-plugins/drone-github-release/index.md

Based on existing docs from https://github.com/drone-plugins/drone-github-release/blob/master/DOCS.md

github-release plugin

---

content/drone-plugins/drone-s3-sync/index.md

Fixes https://github.com/drone-plugins/drone-s3-sync/issues/29

Added docs for drone-plugins/drone-s3-sync

---

content/drone-plugins/drone-gcr/index.md

Pending https://github.com/drone-plugins/drone-docker/pull/144.

Add documentation for updated GCR plugin

---

content/drone-plugins/drone-s3-cache/index.md

Fixes https://github.com/drone-plugins/drone-s3-cache/issues/16

Added docs for drone-plugins/drone-s3-cache

---

content/drillster/drone-email/index.md

Add documentation to drone-email for new attachment feature

---

content/drone-plugins/drone-gcr/index.md

For this: https://github.com/drone-plugins/drone-docker/blob/master/cmd/drone-docker-gcr/main.go#L18-L23.

Update available secrets keys

---

content/drone-plugins/drone-slack/index.md

Docs for https://github.com/drone-plugins/drone-slack/pull/66.

slack: document the new build.pull template variable

---

content/appleboy/drone-ssh/index.md

as title
Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>

update docs for drone-ssh pluging.

---

content/appleboy/drone-scp/index.md

update drone-scp document.

---

content/appleboy/drone-line/index.md

docs: update drone-line docs

---

content/drone-plugins/drone-docker/index.md

Make a note about the debug parameter.

Add debug parameter

---

content/christophschlosser/drone-ftps/index.md

Together with the new upload command the username was moved to the secret section.
See: christophschlosser/drone-ftps#1

docs: Update to new docker image

---

content/lucaperret/drone-now/index.md

Visit https://github.com/lucaperret/drone-now for more informations

feat: Add drone-now plugin

---

content/christophschlosser/drone-ftps/index.md

Add description for the new options: 
```chmod```
```clean_dir```

Add options: chmod, clean_dir in drone-ftps

---

content/christophschlosser/drone-ftps/index.md

See: https://github.com/christophschlosser/drone-ftps

docs: add new SSL option - 'verify' 

---

content/drone-plugins/drone-gitea-release/index.md
static/logos/gitea.svg

Documentation for the [gitea-release-plugin](https://github.com/drone-plugins/drone-gitea-release). 
Fixes drone-plugins/drone-gitea-release#5

Add Gitea Release documentation

---

content/vividboarder/drone-webdav/index.md

Repo https://github.com/ViViDboarder/drone-webdav

Add new plugin for uploading to WebDAV

---

content/drone-plugins/drone-slack-blame/index.md

Fixes https://github.com/drone-plugins/drone-slack-blame/issues/23

Added slack-blame docs

---

content/appleboy/drone-line/index.md

update the drone line docs.

---

content/drone-plugins/drone-s3-cache/index.md

Based on https://github.com/drone-plugins/drone-s3-cache/pull/24/files.
PTAL @donny-dont.

Update s3-cache docs

---

content/drone-plugins/drone-gh-pages/index.md

Fixes https://github.com/drone-plugins/drone-gh-pages/issues/10

Add documentation for the gh-pages plugin

---

content/appleboy/drone-telegram/index.md

Update the content about drone-telegram.

Update drone-telegram document

---

content/drone-plugins/drone-docker/index.md

To be merged after https://github.com/drone-plugins/drone-docker/pull/168

Add build target on docker plugin

---

content/wayneconnolly/drone-rancher-stack-v1/index.md

Please merge this plugin contribution that enables Rancher v1 (1.6) stack deployments/upgrades.

Added docs for drone-rancher-stack-v1 plugin

---

content/drone-plugins/drone-manifest/index.md

Solves https://github.com/drone-plugins/drone-manifest/issues/5

Add docs for drone-plugins/drone-manifest

---

content/techknowlogick/drone-b2/index.md

Minor fixes for drone-b2 documentation

---

content/drone-plugins/drone-pypi/index.md

@tboerger Fixed docs to match https://github.com/drone-plugins/drone-pypi/pull/16

Move docs to drone-pypi and fix 1.0 syntax

---

content/drone-plugins/drone-s3-sync/index.md

Includes description of how the permission is being used

Include permissions required by drone-s3-sync

---

content/drone-plugins/drone-docker/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/drone/drone-plugin-index/182)

add notes on using `purge` key

---

content/drone-plugins/drone-s3-cache/index.md

see drone-plugins/drone-s3-cache#53

add workdir docs

---

content/drone-plugins/drone-downstream/index.md

From https://github.com/drone-plugins/drone-downstream/pull/37

[drone-downstream] Add section about passing env vars

---

content/danielgormly/drone-plugin-kube/index.md

This time based on the provided archetypal document ;). With important additions to the plugin incl. semantic versioning, configmaps from files and watching deployments until they are ready.

Added danielgormly/drone-plugin-kube

---

content/appleboy/drone-ssh/index.md

docs(drone-ssh): update format for 1.0

---

README.md

Update readme informations

---

content/drone-plugins/drone-manifest/index.md

Update drone-plugins/manifest documentation for issue https://github.com/drone-plugins/drone-manifest/pull/29

Added description of `insecure' setting for 'drone-plugins/manifest`

---

content/appleboy/drone-telegram/index.md

1. Example configuration with a custom message template loaded from file
2. Example configuration with a generic message template loaded from file, with additional extra vars
3. Example configuration with a custom socks5 URL

docs(telegram): add some parameter examples

---

content/naorlivne/drone-github-changelog-generator/index.md

This pull request adds a plugin version of https://github.com/github-changelog-generator/github-changelog-generator

adding drone-github-changelog-generator plugin

---

content/appleboy/drone-git-push/index.md

feat: Add git push commit plugin

---

content/appleboy/drone-ssh/index.md

Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>

docs(drone-ssh): add passphrase example

---

content/pelotech/drone-helm3/index.md

(The settings were added in pelotech/drone-helm3#68 and pelotech/drone-helm3#69)
/cc @josmo

Mention new settings for pelotech/drone-helm3

---

content/pelotech/drone-helm3/index.md

Updated/alternate version of #257. This time it's actually ready to go!

Clearer names for pelotech/drone-helm3's settings

---

content/appleboy/drone-discord/index.md

chore(drone-discord): type: discored -> discord

---

content/pelotech/drone-helm3/index.md

New setting added in version 0.12.0 (see pelotech/drone-helm3#74 and pelotech/drone-helm3#75).

Document the repo certificate settings for pelotech/drone-helm3

---

content/appleboy/drone-discord/index.md

chore(drone-discord): update secret setting

---

content/drone-plugins/drone-ecr/index.md

Simple update to add information for a setting that is already available in the plugin, just not documented. 
For reference here is the setting flag in the code itself: https://github.com/drone-plugins/drone-docker/blob/master/cmd/drone-ecr/main.go#L29

doc: update ecr plugin for create variable

---

content/bh90210/dron8s/index.md

I am so sorry all, but I found a spelling error of mine
https://github.com/bh90210/dron8s/issues/8

Documantation spelling error

---

content/appleboy/drone-ssh/index.md

as title. Add new feature for multiple hosts with different port

chore(drone-ssh): multiple hosts with different port

---

content/allgreed/drone-load-and-store/index.md

I don't know what the `date` attribute should really be so I somewhat arbitrarily set it to today's midnight

Add drone-load-and-store plugin

---

content/drone-plugins/drone-ansible/index.md

Hi,
This documents drone-plugins/drone-ansible#44.

Add galaxy_force option to drone-ansible plugin

---

content/bh90210/dron8s/index.md

hello all, 
I made an update to my plugin and thus the documentation!
have a great day :)

plugin documentation update

---

plugins/google-cloud-auth/content.yaml
plugins/google-cloud-run/content.yaml
plugins/java-maven/content.yaml
plugins/vercel-deploy/content.yaml
public/logos/vercel-icon-dark.svg

Added a new plugin to deploy site to vercel.com. Updated the image registries for java-maven, gcloud-run and gcloud-auth

Vercel plugin and  Image Registries Update

---

plugins/google-cloud-auth/content.yaml

- example updates
- description updates

fix: update to use Google Artifact Registry

---

next.config.js
plugins/k8s/content.yaml
plugins/k8s/original.md

This is a more complete plugin that supports all k8s resources.

Add k8s plugin

---

plugins/melange/content.yaml

Add [melange](https://github.com/chainguard-dev/melange) plugin

Add melange plugin

---

plugins/matrixchat-notify/content.yaml

@SpotlightKid this was failing validation - any concerns with my changes please let me know :)
schema can be found here - https://github.com/drone/drone-plugin-index/blob/main/plugin-validation/plugin-schema.json

fix failed validation

---

plugins/gcr/content.yaml
plugins/gcr/original.md

Follow up PR to add docs to the GCR plugin
drone-plugins/drone-docker#383

Update docs with workload identity example
